services:
  db:
    image: postgres:16
    container_name: maloffice_db_dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: maloffice
    ports:
      - "5432:5432"
    volumes:
      - ../postgres/data_dev:/var/lib/postgresql/data
      - ../postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d maloffice"]
      interval: 3s
      timeout: 2s
      retries: 30
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: maloffice_redis_dev
    ports:
      - "6379:6379"
    restart: unless-stopped

  api:
    build: .
    container_name: maloffice_api_dev
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev 
    volumes:
      - ./app:/app/app
      - ../models:/models:ro
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped
